# Use a slim Python base image
FROM python:3.10-slim-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your application code
COPY etl/ ./etl/
COPY utils/ ./utils/
COPY orchestrator.py .
# COPY .env .env # Copy .env for DB credentials etc.  <-- DELETE OR COMMENT THIS LINE OUT!

# Set the entrypoint command
CMD ["python", "orchestrator.py"]